"""empty message

Revision ID: 49ffbd90ef7e
Revises: 5d03a847b91d
Create Date: 2025-11-09 21:36:16.504509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49ffbd90ef7e'
down_revision = '5d03a847b91d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('polls', sa.Column('creator_id', sa.String(), nullable=True))
    # Add princess_mode as nullable first, then set default for existing rows
    op.add_column('polls', sa.Column('princess_mode', sa.Boolean(), nullable=True))
    # Set default value for existing rows
    op.execute("UPDATE polls SET princess_mode = false WHERE princess_mode IS NULL")
    # Now make it non-nullable
    op.alter_column('polls', 'princess_mode', nullable=False, server_default=sa.false())
    
    # Set creator_id to NULL for existing polls that don't have valid users
    # This ensures the foreign key constraint can be added safely
    op.execute("""
        UPDATE polls 
        SET creator_id = NULL 
        WHERE creator_id IS NOT NULL 
        AND creator_id NOT IN (SELECT id FROM users)
    """)
    
    # Now add the foreign key constraint
    op.create_foreign_key(None, 'polls', 'users', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'polls', type_='foreignkey')
    op.drop_column('polls', 'princess_mode')
    op.drop_column('polls', 'creator_id')
    # ### end Alembic commands ###

