"""Initial migration

Revision ID: 5d03a847b91d
Revises: 
Create Date: 2025-11-09 20:55:46.521419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d03a847b91d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('polls',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('winner_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('options',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('poll_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_options_poll', 'options', ['poll_id'], unique=False)
    op.create_table('participants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('poll_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('ready', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_participants_poll_user', 'participants', ['poll_id', 'user_id'], unique=True)
    op.create_table('votes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('poll_id', sa.String(), nullable=False),
    sa.Column('option_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('veto', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['options.id'], ),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_votes_poll_option_user', 'votes', ['poll_id', 'option_id', 'user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_votes_poll_option_user', table_name='votes')
    op.drop_table('votes')
    op.drop_index('ix_participants_poll_user', table_name='participants')
    op.drop_table('participants')
    op.drop_index('ix_options_poll', table_name='options')
    op.drop_table('options')
    op.drop_table('users')
    op.drop_table('polls')
    # ### end Alembic commands ###

